apiVersion: v1
kind: ReplicationController
metadata:
  name: web
spec:
  replicas: 3
  selector:
    web: "true"
  template:
    metadata:
      labels:
        name: web
        web: "true"
        role: web
    spec:
      nodeSelector:
        role: worker
      containers:
      - name: web
        image: larsks/mini-httpd
        env:
          - name: WEB
            value: "true"
        ports:
          - containerPort: 80
