---
# The path to the directory where binaries are stored
# on Ansible managed systems.
bin_path: /usr/local

# The directory used by Ansible to temporarily store
# files on Ansible managed systems.
ansible_temp_dir: /tmp/.ansible/files
