---
- name: Create system kube-cert groups
  group: name={{ kube_cert_group }} state=present system=yes
#  when: not is_coreos

- name: Create system kube user
  user:
    name=kube
    comment="Kubernetes user"
    shell=/sbin/nologin
    state=present
    system=yes
    groups={{ kube_cert_group }}
#  when: not is_coreos

#- name: Create system kube-cert groups for CoreOS
#  raw: sudo /usr/sbin/groupadd {{ kube_cert_group }} -r -f
#  when: is_coreos

#- name: Remove system kube user for CoreOS
#  raw: sudo /usr/sbin/userdel kube -f
#  when: is_coreos

#- name: Create system kube user for CoreOS
#  raw: sudo /usr/sbin/useradd kube -c "Kubernetes user" -s /sbin/nologin -r -g {{ kube_cert_group }}
#  when: is_coreos

- name: make sure the certificate directory exits
  file:
    path={{ kube_cert_dir }}
    state=directory
    mode=o-rwx
    group={{ kube_cert_group }}

- name: make sure the tokens directory exits
  file:
    path={{ kube_token_dir }}
    state=directory
    mode=o-rwx
    group={{ kube_cert_group }}

- include: gen_certs.yml
  when: inventory_hostname == groups['masters'][0]

- name: Read back the CA certificate
  slurp:
    src: "{{ kube_cert_dir }}/ca.crt"
  register: ca_cert
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"

- name: Register the CA certificate as a fact so it can be used later
  set_fact:
    kube_ca_cert: "{{ ca_cert.content|b64decode }}"

- name: Place CA certificate everywhere
  copy: content="{{ kube_ca_cert }}" dest="{{ kube_cert_dir }}/ca.crt"
  notify:
    - restart daemons

- include: gen_tokens.yml
  when: inventory_hostname == groups['masters'][0]
