---
- name: Set selinux permissive because tokens and selinux don't work together
  selinux: state=permissive policy={{ ansible_selinux.type }}
  when: ansible_selinux is defined and ansible_selinux.status == "enabled"

- name: Force source_type to github when coreos
  set_fact:
    source_type: "github-release"
  when: is_coreos

- include: packageManagerInstall.yml
  when: source_type == "packageManager"
  tags:
    - binary-update

- include: localBuildInstall.yml
  when: source_type == "localBuild"
  tags:
    - binary-update

- name: Make sure manifest directory exists
  file: path={{ kube_manifest_dir }} state=directory

- name: Install fluentd pod into each node
  get_url:
    url=https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/saltbase/salt/fluentd-es/fluentd-es.yaml
    dest="{{ kube_manifest_dir }}"
    force=yes
    validate_certs=False
  environment:
    http_proxy: "{{ http_proxy|default('') }}"
    https_proxy: "{{ https_proxy|default('') }}"
  when: cluster_logging

- name: Get the node token values
  slurp:
    src: "{{ kube_token_dir }}/{{ item }}-{{ inventory_hostname }}.token"
  with_items:
    - "system:kubelet"
    - "system:proxy"
  register: tokens
  delegate_to: "{{ groups['masters'][0] }}"

- name: Set token facts
  set_fact:
    kubelet_token: "{{ tokens.results[0].content|b64decode }}"
    proxy_token: "{{ tokens.results[1].content|b64decode }}"

- name: Install from github
  include: github-release.yml
  when: source_type == "github-release"

- name: Add Kube Systemd Unit File
  template: src={{ item }}.service dest=/etc/systemd/system/{{ item }}.service
  register: "{{ item }}_service"
  notify:
    - reload systemd
  with_items:
    - kubelet
    - kube-proxy
  when: is_coreos

- name: Create the /var/lib/kubelet working directory
  file:
    path: /var/lib/kubelet
    state: directory

- name: write the config files for kubelet
  template: src=kubelet.j2 dest={{ kube_config_dir }}/kubelet
  notify:
    - restart kubelet

- name: write the kubecfg (auth) file for kubelet
  template: src=kubelet.kubeconfig.j2 dest={{ kube_config_dir }}/kubelet.kubeconfig
  notify:
    - restart kubelet

- name: Enable kubelet
  service: name=kubelet enabled=yes 
  notify:
    - restart kubelet

- name: write the config files for proxy
  template: src=proxy.j2 dest={{ kube_config_dir }}/proxy
  notify:
    - restart proxy

- name: write the kubecfg (auth) file for kube-proxy
  template: src=proxy.kubeconfig.j2 dest={{ kube_config_dir }}/proxy.kubeconfig
  notify:
    - restart proxy

- name: Enable proxy
  service: name=kube-proxy enabled=yes state=started
  when: networking != "opencontrail"

- include: firewalld.yml
  when: has_firewalld

- include: iptables.yml
  when: not has_firewalld and has_iptables
