---
galaxy_info:
  author: Bert Van Vreckem
  description: Installs and configures a TFTP (Trivial File Transfer Protocol) server on RHEL/CentOS 7
  company:
  license: BSD
  min_ansible_version: 1.7
  platforms:
  - name: EL
    versions:
      - 7
  categories:
    - networking
  galaxy_tags:
    - version: 1.2.0
dependencies: []
