---
- name: Check if netbootstrap is needed
  sudo: yes
  raw: stat {{ kube_script_dir }}/.netbootstrapped
  register: need_netbootstrap
  ignore_errors: True

- name: Run netbootstrap.sh
  sudo: yes
  script: netbootstrap.sh --interface {{ kube_internal_interface }} --ip {{ kube_internal_ip }} --cidr {{ kube_internal_cidr }}
  environment:
    KUBE_SCRIPT_DIR: "{{ kube_script_dir }}"
  when: need_netbootstrap | failed
