---

- name: CoreOS | Create docker dropin directory
  file: path=/etc/systemd/system/docker.service.d state=directory mode=0755

- name: CoreOS | Write docker dropin file
  template: src=10-env-file.config.j2 dest="/etc/systemd/system/docker.service.d/10-env-file.conf"
  register: docker_dropin
  notify:
    - reload systemd
