---
# This playbook deploys a kubernetes cluster 
# with the default addons.

- hosts: all
  gather_facts: false
  sudo: yes
  roles:
    - pre-ansible
  tags:
    - pre-ansible

# Install etcd
- hosts: etcd
  sudo: yes
  roles:
    - etcd
  tags:
    - etcd

- hosts: all
  sudo: yes
  roles:
    - common
    - docker
  tags:
    - docker

# install kube master services
- hosts: masters
  sudo: yes
  roles:
    - { role: flannel, when: networking == 'flannel' }
    - { role: opencontrail, when: networking == 'opencontrail'}
    - { role: contiv, contiv_role: netmaster, when: networking == 'contiv' }
    - master
    - kubernetes-addons
  tags:
    - masters
    - addons
    - dns
    - network-service-install

# install kubernetes node services
- hosts: nodes
  sudo: yes
  roles:
    - { role: flannel, when: networking == 'flannel' }
    - { role: contiv, contiv_role: netplugin, when: networking == 'contiv' }
    - { role: opencontrail, when: networking == 'opencontrail'}
    - node
  tags:
    - nodes
    - network-service-install

# provision opencontrail once dependant services are operational
- hosts:
    - masters[0]
    - nodes
  sudo: yes
  roles:
    - { role: opencontrail-provision, when: networking == 'opencontrail' }
  tags:
    - network-service-config
