---
# This playbook deploys a kubernetes cluster 
# with the default addons.

#- name: print out operating system
#  hosts: all
#  gather_facts: True
#  tasks:
#  - debug: var=ansible_distribution

- hosts: all
  gather_facts: false
  sudo: yes
  roles:
    - pre-ansible
  tags:
    - pre-ansible

# Install etcd
- hosts: etcd
  sudo: yes
  roles:
    - etcd
  tags:
    - etcd

- hosts: all
  sudo: yes
  roles:
    - common
    - docker
  tags:
    - docker

# install flannel
- hosts:
    - etcd
    - masters
    - nodes
  sudo: yes
  roles:
    - { role: flannel, when: networking == 'flannel' }
  tags:
    - network-service-install

# install kube master services
- hosts: masters
  sudo: yes
  roles:
    - master
  tags:
    - masters

# launch addons, like dns
- hosts: masters
  sudo: yes
  roles:
    - kubernetes-addons
  tags:
    - addons
    - dns

# install kubernetes on the nodes
- hosts: nodes
  sudo: yes
  roles:
    - node
  tags:
    - nodes
